### ISSUE TITLE
npm run dev 报错 

### ISSUE THREAD

**Issue by wenchangming211** [cdswyda/weekly-report#1]
ERROR  Failed to compile with 5 errors                                                                                                                                              4:20:22 AM

These dependencies were not found:

* @/config/av.config.js in ./src/api/init.js
* iview/src/components/Message/ in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/input.vue
* iview/src/components/Modal/index.js in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/signup.vue, ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/input.vue

To install them, you can run: npm install --save @/config/av.config.js iview/src/components/Message/ iview/src/components/Modal/index.js

This relative module was not found:

* ./userInfo in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/header.vue
> Listening at http://localhost:8066

**Comment by cdswyda** [comment]
About the `@/config/av.config.js in ./src/api/init.js` question, maybe you didn't do them:

> 修改 `src/config/av.config-example.js` 文件，填入 LeanCloud 应用的 **App ID** 和 **App key**。  
> 此 `id` 和 `key` 可以从 [LeanCloud](https://leancloud.cn/)  `要关联的应用 => 设置 => 应用 Key` 中获取。

```js
// 填写配置后重命名此文件为av.config.js
export default {
  id: '填写LeanCloud应用的ID',
  key: '填写LeanCloud应用的Key'
}
```
