### ISSUE TITLE
JSON文件导入不了

### ISSUE THREAD

**Issue by wangcongyi** [cdswyda/weekly-report#13]
在 leancloud 新增应用之后 JSON文件导入不了
![image](https://user-images.githubusercontent.com/13843979/54325364-bf1f6a80-463c-11e9-92eb-6b8e3af77503.png)
![image](https://user-images.githubusercontent.com/13843979/54325389-e0805680-463c-11e9-8a05-522098cc88ce.png)
![image](https://user-images.githubusercontent.com/13843979/54325396-e5450a80-463c-11e9-8c01-ca89421966e4.png)

是我导入的方式不对还是 leancloud 的错误？

**Comment by wangcongyi** [comment]
是否可以不依赖 leancloud ？

**Comment by cdswyda** [comment]
(⊙o⊙)… 

上面这个是 leancloud 自带的东西，是没有用到的，是无须导入的。是我的问题，之前未将无用文件进行移除。目前已经重新整理提交了。

以 `_`  开头的都是 leancloud 的自带的一般无须修改， 本应用中 用户 和 角色是直接应用的， 即 `_User` 和 `_Role` 需要导入。

ps： 导入成功 0 条， 本身也是正常的， 因为导入的本身就只是 `schema` 其是不含任何数据的， 类似于数据库的表结构。

**Comment by cdswyda** [comment]
刚开始做这个的时候，还是一个初入前端半年的小子，虽然有做抽取，但目前来看，耦合还是比较重的。。。

因此不依赖 leancloud 改造成本还是不小的， 此外由于之前水平原因，一些实现上并不是很好。。。

**Comment by wangcongyi** [comment]
@cdswyda 嗯，基本上都是 leancloud-storage
PS：代码格式可以啊，但部分还是没有根据 eslint 来；echarts 有 vue 的组件；

**Comment by wangcongyi** [comment]
@cdswyda 告知下QQ 还是不行
