### ISSUE TITLE
因为公司网络限制，无法访问leancloud。请问如果不使用leadcloud提供服务，使用本地提供服务，改造量会很大吗，有什么建议?

### ISSUE THREAD

**Issue by likangda** [cdswyda/weekly-report#2]

**Comment by cdswyda** [comment]
使用 LeanCloud 做存储和读取的api基本都写写在 `/src/api/`  下，可以自行使用其他方式实现类似的操作即可，除此之外，关于用户登录的需要微调下即可。

**Comment by cdswyda** [comment]
@likangda 
其实经过开发之后发现其实 Leancloud 并不是一个很好的选择，做类似于数据库的join查询时，很不方便（可能是我对它机制的理解不够）

如果你有改造，欢迎pull Request给我，谢谢！
