### ISSUE TITLE
你好，能帮我看看一个问题吗？注册页面这样报错，登录页面也无法填写信息

### ISSUE THREAD

**Issue by 20000109sun** [cdswyda/weekly-report#31]
Failed to load resource: the server responded with a status of 403 ()
iqlre3ax.api.lncldglobal.com/1.1/classes/Group?where=%7B%7D&limit=1000&order=index:1 
 Failed to load resource: the server responded with a status of 404 ()
error.js?6183:4 Error: Class or object doesn't exists. [404 GET https://iqlre3ax.api.lncldglobal.com/1.1/classes/Group]
    at eval (av-min.js?23f1:1:1)
    at C (av-min.js?23f1:15:1)
    at E (av-min.js?23f1:15:1)
    at S (av-min.js?23f1:15:1)
    at b (av-min.js?23f1:15:1)
    at MutationObserver.u (av-min.js?23f1:15:1)

**Comment by cdswyda** [comment]
已经不再维护，不做技术支持。 

403的问题， 可尝试检查leanclound上权限设置（需开启客户端创建class或object等） 或 api相关。

后面404的错误，提示已经很明显了 ` Error: Class or object doesn't exists. ` class 或 object 不存在。
